name: Snyk Actions
run-name: ${{ github.actor }} is testing out Github Actions

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      # Optional: Uploads the dependency graph to GitHub for Dependabot alerts
      - name: Update dependency graph
        uses: advanced-security/gradle-dependency-submission-action@v1

  opensource-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./gradlew
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

  code-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Gradle Wrapper is executable
        run: chmod +x ./gradlew
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
        continue-on-error: true
